### ISSUE TITLE
Cannot find generateSecurityPreferences method.

### ISSUE THREAD

**Issue by ffwd-jeonguk** [taehwandev/EncryptedDataStorePreference#12]
```
class MainActivity : ComponentActivity() {

    private val Context.dataStore by preferencesDataStore(name = "security-preference")

    private val securityPreference: SecurityPreferences by lazy {
        dataStore.generateSecurityPreferences(generateUsefulSecurity())
    }
    ...
```

안녕하세요. 해당 라이브러리를 보며 영감을 얻고 있었는데 최근에 많은 부분이 개선된 것으로 보입니다.
개선 과정에서 app모듈의 MainActivity에서 generateSecurityPreferences라는 함수가 추가 된 것으로 보이는데 소스코드내에 해당 함수가 작성되어 있는 부분을 찾아볼 수 없어서 이슈 생성 합니다. 확인 부탁드립니다!

**Comment by taehwandev** [comment]
@ffwd-jeonguk 안녕하세요.
해당 코드는 처음부터 동일한 위치에 있었는데 generate[Preference name interface]로 합성됩니다.

합성 위치는 아래 링크를 참고하세요.

https://github.com/taehwandev/EncryptedDataStorePreference/blob/main/useful-encrypted-data-store-preferences-ksp/src/main/java/tech/thdev/useful/encrypted/data/store/preferences/ksp/internal/generate/GeneratePreferences.kt#L193
